package clasesBaseDeDatos;
// Generated 14 ene 2025, 16:15:44 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idCliente;
	private String dni;
	private String nombre;
	private String direccion;
	private String ciudad;
	private String telefono;
	private String email;
	private Byte edad;
	private String sexo;
	private Set ventas = new HashSet(0);

	public Cliente() {
	}

	public Cliente(int idCliente, String dni, String nombre, String direccion, String ciudad, String telefono,
			String email) {
		this.idCliente = idCliente;
		this.dni = dni;
		this.nombre = nombre;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.telefono = telefono;
		this.email = email;
	}

	public Cliente(int idCliente, String dni, String nombre, String direccion, String ciudad, String telefono,
			String email, Byte edad, String sexo, Set ventas) {
		this.idCliente = idCliente;
		this.dni = dni;
		this.nombre = nombre;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.telefono = telefono;
		this.email = email;
		this.edad = edad;
		this.sexo = sexo;
		this.ventas = ventas;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Byte getEdad() {
		return this.edad;
	}

	public void setEdad(Byte edad) {
		this.edad = edad;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Set getVentas() {
		return this.ventas;
	}

	public void setVentas(Set ventas) {
		this.ventas = ventas;
	}

}
