package clasesBaseDeDatos;
// Generated 14 ene 2025, 16:15:44 by Hibernate Tools 5.6.15.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Coches generated by hbm2java
 */
public class Coches implements java.io.Serializable {

	private int idCoche;
	private String marca;
	private String modelo;
	private String color;
	private String matricula;
	private byte plazas;
	private String extras;
	private Set ventas = new HashSet(0);

	public Coches() {
	}

	public Coches(int idCoche, String marca, String modelo, String color, String matricula, byte plazas) {
		this.idCoche = idCoche;
		this.marca = marca;
		this.modelo = modelo;
		this.color = color;
		this.matricula = matricula;
		this.plazas = plazas;
	}

	public Coches(int idCoche, String marca, String modelo, String color, String matricula, byte plazas, String extras,
			Set ventas) {
		this.idCoche = idCoche;
		this.marca = marca;
		this.modelo = modelo;
		this.color = color;
		this.matricula = matricula;
		this.plazas = plazas;
		this.extras = extras;
		this.ventas = ventas;
	}

	public int getIdCoche() {
		return this.idCoche;
	}

	public void setIdCoche(int idCoche) {
		this.idCoche = idCoche;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public byte getPlazas() {
		return this.plazas;
	}

	public void setPlazas(byte plazas) {
		this.plazas = plazas;
	}

	public String getExtras() {
		return this.extras;
	}

	public void setExtras(String extras) {
		this.extras = extras;
	}

	public Set getVentas() {
		return this.ventas;
	}

	public void setVentas(Set ventas) {
		this.ventas = ventas;
	}

}
