package clasesBaseDeDatos;
// Generated 14 ene 2025, 16:15:44 by Hibernate Tools 5.6.15.Final

import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private int idVenta;
	private Cliente cliente;
	private Coches coches;
	private Date fechaCompra;
	private Date fechaEntrega;
	private int precio;

	public Venta() {
	}

	public Venta(int idVenta, Cliente cliente, Coches coches, Date fechaCompra, int precio) {
		this.idVenta = idVenta;
		this.cliente = cliente;
		this.coches = coches;
		this.fechaCompra = fechaCompra;
		this.precio = precio;
	}

	public Venta(int idVenta, Cliente cliente, Coches coches, Date fechaCompra, Date fechaEntrega, int precio) {
		this.idVenta = idVenta;
		this.cliente = cliente;
		this.coches = coches;
		this.fechaCompra = fechaCompra;
		this.fechaEntrega = fechaEntrega;
		this.precio = precio;
	}

	public int getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(int idVenta) {
		this.idVenta = idVenta;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Coches getCoches() {
		return this.coches;
	}

	public void setCoches(Coches coches) {
		this.coches = coches;
	}

	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public int getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

}
